#!/bin/zsh

local PWD=`pwd`
echo ''
echo '#====================#'
echo '# Rebase Repository  #'
echo '#====================#'
git stash clear
git stash
git pull --rebase

echo ''
echo '#====================#'
echo '# Replace Rcfiles    #'
echo '#====================#'
rm -f ~/.screenrc ; ln -s $PWD/screenrc ~/.screenrc && echo 'o -> ~/.screenrc'
rm -f ~/.toprc    ; ln -s $PWD/toprc    ~/.toprc    && echo 'o -> ~/.toprc'
rm -f ~/.vim      ; ln -s $PWD/vim      ~/.vim      && echo 'o -> ~/.vim/'
rm -f ~/.vimrc    ; ln -s $PWD/vimrc    ~/.vimrc    && echo 'o -> ~/.vimrc'
rm -f ~/.zsh      ; ln -s $PWD/zsh      ~/.zsh      && echo 'o -> ~/.zsh/'
rm -f ~/.zshrc    ; ln -s $PWD/zshrc    ~/.zshrc    && echo 'o -> ~/.zshrc'
rm -f ~/.zshenv   ; ln -s $PWD/zshenv   ~/.zshenv   && echo 'o -> ~/.zshenv'

echo ''
echo '#====================#'
echo '# Update submodules  #'
echo '#====================#'
git submodule init
git submodule update
git submodule foreach 'git pull origin master'

echo ''
echo '#=====================#'
echo '# Install Vim Bundles #'
echo '#=====================#'
echo 'Vundle: Installing bundles...'
echo ':BundleInstall' | vim > /dev/null 2>&1
echo 'Vundle: Cleaning bundles...'
echo ':BundleClean'   | vim > /dev/null 2>&1

echo ''
echo '#=====================#'
echo '# Retouch Alters      #'
echo '#=====================#'
git stash pop

echo ''
echo '#========================#'
echo '# All Process Finished!! #'
echo '#========================#'
echo ''
