set-window-option -g utf8 on
set-window-option -g mode-keys vi
set-window-option -g automatic-rename off

set -s escape-time 0
setw -g window-status-current-attr underscore

set-option -g default-terminal "screen-256color"
set-option -g status-interval 5

set -g pane-active-border-fg white
set -g pane-active-border-bg black

set-window-option -g mode-bg white
set-window-option -g mode-fg black
set-window-option -g window-status-bg black
set-window-option -g window-status-fg white
set-window-option -g window-status-current-bg blue
set-window-option -g window-status-current-fg black
set-window-option -g window-status-current-attr bold

unbind ^b
set-option -g prefix ^A
bind a send-prefix

bind c new-window -n zsh
bind ^C new-window -n zsh

bind d detach
bind ^D detach

bind * list-clients

bind ^W list-windows
bind w list-windows

bind ^A last-window
bind a last-window

bind ^N next-window
bind n next-window

bind ^P previous-window
bind p previous-window

bind ^R command-prompt "rename-window %%"
bind r source-file ~/.tmux.conf

unbind ^"["
bind -r ^"[" copy-mode
unbind ^]
bind -r ^] paste-buffer

bind -t vi-copy v begin-selection
bind -t vi-copy y copy-selection

bind ^K confirm-before "kill-window"
bind k confirm-before "kill-window"

bind ^S split-window
bind s split-window

unbind Tab
bind Tab select-pane -t :.-
unbind BTab
bind BTab select-pane -t :.+
unbind ^H
bind ^H select-pane -t :.-
unbind h
bind ^h select-pane -t :.-
unbind ^L
bind ^L select-pane -t :.+
unbind l
bind l select-pane -t :.+

unbind '"'
bind '"' choose-window

set-option -g set-titles on
set-option -g set-titles-string "[#I:#P] #H"

set-option -g status-attr dim
set-option -g status-left-length 32
set-option -g status-right-length 60

set-option -g status-fg white
set-option -g status-bg colour234
set-option -g pane-border-fg colour245
set-option -g pane-active-border-fg colour39

set-option -g status-left '\
#[fg=colour223, bg=colour202] #H #S #[fg=colour202,bg=colour238]⮀\
#[fg=colour245, bg=colour238] #(whoami) #[fg=colour234, bg=colour234]⮀ '
set-option -g window-status-format "#[fg=white, bg=colour234] #I #W "
set-option -g window-status-current-format "#[fg=colour255, bg=colour39] #I #W "

set-option -g status-right '\
#[fg=colour235]⮂#[fg=colour254,bg=colour239]#(w | head -n1 | cut -d":" -f4) #(osx-cpu-temp) \
#[fg=colour240]⮂#[fg=colour254,bg=colour243] M #(echo $\(\( 100 - `vm_stat | tail -n +2 | head -n -11 | sed "s/[:| |\.]*//g" | sed "s/[A-Za-z]//g"` * 100 / \
\(`vm_stat | tail -n +6 | head -n -7 | sed "s/[:| |\.]*//g" | sed "s/[A-Za-z]//g"` + \
`vm_stat | tail -n +3 | head -n -10 | sed "s/[:| |\.]*//g" | sed "s/[A-Za-z]//g"` + \
`vm_stat | tail -n +4 | head -n -9 | sed "s/[:| |\.]*//g" | sed "s/[A-Za-z]//g"` + \
`vm_stat | tail -n +2 | head -n -11 | sed "s/[:| |\.]*//g" | sed "s/[A-Za-z]//g"` \) \)\))%% \
#[fg=colour245]⮂#[fg=colour233,bg=colour247] D #(df | tail -n +2 | head -n -1 | sed "s/  */ /g" | cut -d" " -f5-5) \
#[fg=colour250]⮂#[fg=colour233,bg=colour252] %Y.%m.%d %H:%M '
set-option -g message-attr bold
set-option -g message-fg white
set-option -g message-bg red

