# OPTION
## WINDOW
set-window-option -g utf8 on
set-window-option -g mode-keys vi
set-window-option -g mode-mouse on
set-window-option -g automatic-rename on

## GLOBAL
set-option -s escape-time 0

set-option -g status-utf8 on
set-option -g mouse-utf8 on
set-option -g status-interval 5
set-option -g default-terminal "screen-256color"
set-option -g terminal-overrides "xterm*:kLFT5=\eOD:kRIT5=\eOC:kUP5=\eOA:kDN5=\eOB:smkx@:rmkx@:colors=256"
set-option -g set-titles on
set-option -g monitor-activity on
set-option -g visual-activity on
set-option -g visual-content on

set-option -g bell-action none
set-option -g visual-bell on
set-option -g display-panes-time 1500
set-option -g display-time 1500

set-option -g default-shell /bin/zsh
set-option -g default-command /bin/zsh

set-option -g status on
set-option -g status-interval 2
set-option -g status-utf8 on
set-option -g status-fg white
set-option -g status-bg colour234
set-option -g status-attr dim
set-option -g status-justify "centre"
set-option -g status-left-length 200
set-option -g status-right-length 200
set-option -g status-left "#(~/.tmux/powerline.sh left)"
set-option -g status-right "#(~/.tmux/powerline.sh right)"

# KEY BINDING
## RE-
bind ^R command-prompt "rename-window %%"
bind r source-file ~/.tmux.conf

## PREFIX
unbind ^b
set-option -g prefix ^A
bind a send-prefix

## WINDOW
bind c new-window -c "#{pane_current_path}" -n -
bind ^C new-window -c "#{pane_current_path}" -n -

bind ^A last-window
bind a last-window

bind d confirm-before detach
bind ^D confirm-before detach

bind ^K confirm-before "kill-window"
bind k confirm-before "kill-window"

# PANE
bind ^I display-panes
bind i display-panes

bind ^S split-window -c "#{pane_current_path}" -v
bind s split-window -c "#{pane_current_path}" -v

bind ^V split-window -c "#{pane_current_path}" -h
bind v split-window -c "#{pane_current_path}" -h

bind ^X swap-pane -D
bind x swap-pane -U

bind \ select-layout even-horizontal
bind | select-layout main-vertical

bind - select-layout even-vertical
bind _ select-layout main-horizontal

# SELECT
unbind ^"["
bind -r ^"[" copy-mode
unbind ^]
bind -r ^] paste-buffer

bind -t vi-copy v begin-selection
bind -t vi-copy y copy-selection

