#!/bin/zsh

function error () {
  echo '#====================#'
  echo '# Something Error    #'
  echo '#====================#'
  echo ''
  echo $1
  echo ''
  echo '#=====================#'
  echo '# Retouch Archives    #'
  echo '#=====================#'
  git stash pop
  echo ''
  exit 1
}

echo '                                    __'
echo '  __  ______  ____ __________ _____/ /__'
echo ' / / / / __ \/ __ `/ ___/ __ `/ __  / _ \'
echo '/ /_/ / /_/ / /_/ / /  / /_/ / /_/ /  __/'
echo '\__,_/ .___/\__, /_/   \__,_/\__,_/\___/'
echo '    /_/__  /____/  _____ __'
echo '  ____/ /___  / /_/ __(_) /__  _____'
echo ' / __  / __ \/ __/ /_/ / / _ \/ ___/'
echo '/ /_/ / /_/ / /_/ __/ / /  __(__  )'
echo '\__,_/\____/\__/_/ /_/_/\___/____/'
echo ''

if [ ! -n "`ls .git 2>/dev/null`" ]; then
  error "'`pwd`' isnt working directory."
fi

if [ ! -s `which git` ]; then
  error 'Your system lack of git.'
fi

echo ''
echo '#====================#'
echo '# Rebase Repository  #'
echo '#====================#'
git stash clear
git stash
git pull --rebase

echo ''
echo '#====================#'
echo '# Replace Rcfiles    #'
echo '#====================#'
rm -f ~/.tmux.conf && ln -s `pwd`/tmux.conf ~/.tmux.conf && echo 'o -> ~/.tmux.conf'
rm -f ~/.vim       && ln -s `pwd`/vim       ~/.vim       && echo 'o -> ~/.vim/'
rm -f ~/.vimrc     && ln -s `pwd`/vimrc     ~/.vimrc     && echo 'o -> ~/.vimrc'
rm -f ~/.zsh       && ln -s `pwd`/zsh       ~/.zsh       && echo 'o -> ~/.zsh/'
rm -f ~/.zshrc     && ln -s `pwd`/zshrc     ~/.zshrc     && echo 'o -> ~/.zshrc'
rm -f ~/.zshenv    && ln -s `pwd`/zshenv    ~/.zshenv    && echo 'o -> ~/.zshenv'

echo ''
echo '#====================#'
echo '# Update submodules  #'
echo '#====================#'
git submodule init
git submodule update
git submodule foreach 'git pull origin master'

echo ''
echo '#====================#'
echo '# Update gitconfig   #'
echo '#====================#'
user=`cat ~/.gitconfig | grep -E '(\[user\]|name.*=|email.*=)'`
conf=`cat gitconfig`
echo $user $conf > ~/.gitconfig
cat gitignore > ~/.gitignore

echo ''
echo '#=====================#'
echo '# Install Vim Bundles #'
echo '#=====================#'
echo 'NeoBundle: Installing bundles...'
echo ':NeoBundleInstall' | vim > /dev/null 2>&1
echo 'NeoBundle: Cleaning bundles...'
echo ':NeoBundleClean'   | vim > /dev/null 2>&1

if [ ${OSTYPE:0:6} = 'darwin' ]; then
  echo ''
  echo '#=====================#'
  echo '# Check HomeBrew      #'
  echo '#=====================#'
  if [ ! -s `which brew` ]; then
    error 'brew not installed: ruby < `curl -fsSkL raw.github.com/mxcl/homebrew/go`'
  else
    echo 'Update HomeBrew...'
    brew update > /dev/null
    if [ ! -d /usr/local/Cellar/coreutils ]; then
      echo 'Install coreutils...'
      brew install coreutils 2>&1 > /dev/null
    fi
  fi
fi

echo ''
echo '#=====================#'
echo '# Retouch Archives    #'
echo '#=====================#'
git stash pop

echo ''
echo '#=====================#'
echo '# All Upgrade Done    #'
echo '#=====================#'
echo ''
