### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk

# Environment
export PATH="$HOME/.anyenv/bin:$PATH"

# Aliases
alias q=exit
alias ls="ls --group-directories-first --color=auto"

# Functions
function psx() {  
  ps ax | grep -v grep | grep -i $1
}                 
function count() {
  echo $(( `ls -l | wc -l`-1 )) `du -sh $@`
}                 
function killgrep() {
  for p in `ps -ef | grep -v grep | grep "$1" | awk '{ print $2 }'`; kill -s KILL "$p"
}       

# Chpwd: Show file list after change directory.
function chpwd {
  ls -F --group-directories-first --color=auto
}

# Z: Tracks your most used directories, based on 'frecency'.
[[ -f /usr/local/etc/profile.d/z.sh ]] && . /usr/local/etc/profile.d/z.sh
                  
# Direnv: Hook envrc file to load custom env.
[[ -x `which direnv` ]] && eval "$(direnv hook zsh)"

# Editor: Use neovim
export VISUAL="`which nvim`"
export EDITOR="`which nvim`"
export SUDO_EDITOR="`which nvim`"
[[ -x "`which nvim`" ]] && alias vi=nvim
[[ -x "`which nvim`" ]] && alias vim=nvim

# Prompt: Powerlevel10k
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
zinit ice depth=1; zinit light romkatv/powerlevel10k

# Plugins
zinit light zinit-zsh/z-a-submods
zinit light zsh-users/zsh-autosuggestions
zinit light zdharma/fast-syntax-highlighting
zinit light zdharma/history-search-multi-word

# Prezto
zinit snippet PZTM::helper
zinit snippet PZTM::utility
zinit snippet PZTM::completion
zinit snippet PZTM::directory

zinit snippet PZTM::osx
zinit snippet PZTM::homebrew
zinit snippet PZTM::gnu-utility

zinit ice submods'zsh-users/zsh-autosuggestions -> external'
zinit snippet PZTM::autosuggestions

zinit snippet PZTM::ssh
zinit snippet PZTM::node
zinit snippet PZTM::ruby

zstyle ':prezto:*:*' color 'yes'
zstyle ':prezto:module:utility' safe-ops 'yes'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
